### ISSUE TITLE
Documentation should mention app.secret

### ISSUE THREAD

**Issue by incredimike** [roelofjan-elsinga/aloia-cms-gui#28]
I was running into issues because Config::get('app.secret') wasn't set for JWT, but it wasn't mentioned in the docs.

**Comment by jesse-deboer** [comment]
Should be fixed with https://github.com/roelofjan-elsinga/aloia-cms-gui/commit/2f928ae50616f9c0b069da6184de51a0adecb9a2!

I think @roelofjan-elsinga can close this one!

**Comment by roelofjan-elsinga** [comment]
I've made a mention of app.secret in the README and also on the documentation website: https://aloiacms.com/aloia-cms-gui

Good catch!
