### ISSUE TITLE
Installation files on new Laravel project

### ISSUE THREAD

**Issue by rabol** [roelofjan-elsinga/aloia-cms-gui#55]
The installation fails with this error:

  Problem 1
    - roelofjan-elsinga/aloia-cms-gui[3.6.0, ..., 3.6.1] require illuminate/support ^6.0|^7.0|^8.0 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires roelofjan-elsinga/aloia-cms-gui ^3.6 -> satisfiable by roelofjan-elsinga/aloia-cms-gui[3.6.0, 3.6.1].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require roelofjan-elsinga/aloia-cms-gui:*" to figure out if any version is installable, or "composer require roelofjan-elsinga/aloia-cms-gui:^2.1" if you know which you need.

Steps:

create a new Laravel 9 project
install the aloia-cms package
then install the aloia-cms-ui package

**Comment by roelofjan-elsinga** [comment]
Correct, I haven't had the time to make this compatible with Laravel 9 and PHP 8 yet.

It's currently compatible with PHP 7.4 and Laravel 6, 7, and 8

**Comment by roelofjan-elsinga** [comment]
Commit 684a043016dca11fc821e012ba864ffdf7a374dd solved this issue.
